ingestion:
  db_name: ${NEO4J_DATABASE}
  urls:
    person: ${PERSON_URL}
    education: ${EDUCATION_URL}
    experience: ${EXPERIENCE_URL}
    language: ${LANGUAGE_URL}
    honour_and_awards: ${HONOUR_AND_AWARDS_URL}
    recommendation: ${RECOMMENDATION_URL}
    blog: ${BLOG_URL}
    projects: ${PROJECT_URL}
    certifications: ${CERTIFICATION_URL}

embedding-model:
  model: HuggingFace
  model-name: all-MiniLM-L6-v2
  api-key: ${HF_TOKEN}

llm-model:
  provider: ChatGroq
  api-key: ${GROQ_API_KEY}
  model: gemma2-9b-it
  base-url: https://api.groq.com/openai/v1
  context-window: 8192