ingestion:
  db_name: ${NEO4J_DATABASE}
  urls:
    person: ${PERSON_URL}
    education: ${EDUCATION_URL}
    experience: ${EXPERIENCE_URL}
    language: ${LANGUAGE_URL}
    honour_and_awards: ${HONOUR_AND_AWARDS_URL}
    recommendation: ${RECOMMENDATION_URL}
    blog: ${BLOG_URL}
    projects: ${PROJECT_URL}
    certifications: ${CERTIFICATION_URL}

embedding-models:
  model: "HuggingFace"
  settings:
    base-url: "base-url"
    model-name: "model-name"
    api-key: ${HF_TOKEN}
    batch-size: 16
    rpm: 60
    tpm: 1000